function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 08-May-2022
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Create empty mask.
BW = false(size(X,1),size(X,2));

% Draw Ellipse
xPos = [486.8603 484.7496 478.4814 468.2439 454.3374 437.1561 417.1675 394.8909 370.8791 345.7032 319.9438 294.1843 269.0085 244.9967 222.7201 202.7315 185.5502 171.6436 161.4062 155.1380 153.0272 155.1380 161.4062 171.6436 185.5502 202.7315 222.7201 244.9967 269.0085 294.1843 319.9438 345.7032 370.8791 394.8909 417.1675 437.1561 454.3374 468.2439 478.4814 484.7496 486.8603];
yPos = [265.9456 293.9058 321.1243 346.8895 370.5460 391.5155 409.3105 423.5391 433.9056 440.2051 442.3180 440.2051 433.9056 423.5391 409.3105 391.5155 370.5460 346.8895 321.1243 293.9058 265.9456 237.9854 210.7669 185.0017 161.3452 140.3756 122.5807 108.3520 97.9856 91.6861 89.5732 91.6861 97.9856 108.3520 122.5807 140.3756 161.3452 185.0017 210.7669 237.9854 265.9456];
m = size(BW, 1);
n = size(BW, 2);
addedRegion = poly2mask(xPos, yPos, m, n);
BW = BW | addedRegion;

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

